import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Clock3, ExternalLink, MapPin, Phone } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Button } from "@/components/ui/button";
import { directionsUrl, phone, phoneHref } from "@/lib/hospital";
import exterior from "@/assets/hospital-exterior.jpg.asset.json";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact & Directions | Entebbe Regional Referral Hospital" }, { name: "description", content: "Find Entebbe Regional Referral Hospital on Nsamizi Road, Entebbe. Get directions and contact information before your visit." }, { property: "og:title", content: "Contact & Directions | Entebbe Regional Referral Hospital" }, { property: "og:description", content: "Directions and contact information for Entebbe Regional Referral Hospital in Uganda." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage() { return <><PageHero eyebrow="Contact & directions" title="We’re here when you need us." description="Find your way to the hospital, get in touch and plan your visit with confidence." />
  <section className="site-container grid gap-12 py-16 lg:grid-cols-[1fr_1fr] lg:items-center lg:gap-20 lg:py-24"><div><p className="eyebrow mb-5 text-primary">Find us</p><h2 className="section-title">Your visit starts here<span className="text-primary">.</span></h2><p className="mt-5 max-w-lg text-base leading-8 text-ink-soft">Entebbe Regional Referral Hospital is located on Nsamizi Road in Entebbe, Uganda. If you need information about a specific clinic, please call ahead.</p><div className="mt-9 divide-y divide-border border-y border-border"><div className="flex gap-5 py-6"><span className="grid size-11 shrink-0 place-items-center rounded-sm bg-sage text-primary"><MapPin className="size-5" /></span><div><h3 className="font-semibold">Visit us</h3><p className="mt-1 text-sm text-muted-foreground">Nsamizi Road, Entebbe, Uganda</p><a href={directionsUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1.5 text-sm font-bold text-primary hover:underline">Open directions <ExternalLink className="size-3.5" /></a></div></div><div className="flex gap-5 py-6"><span className="grid size-11 shrink-0 place-items-center rounded-sm bg-sage text-primary"><Phone className="size-5" /></span><div><h3 className="font-semibold">Call us</h3><a href={phoneHref} className="mt-1 block text-sm text-muted-foreground hover:text-primary">{phone}</a><p className="mt-2 text-xs text-muted-foreground">Please confirm availability before travelling.</p></div></div><div className="flex gap-5 py-6"><span className="grid size-11 shrink-0 place-items-center rounded-sm bg-sage text-primary"><Clock3 className="size-5" /></span><div><h3 className="font-semibold">Laboratory services</h3><p className="mt-1 text-sm text-muted-foreground">Available 24 hours a day, 7 days a week</p></div></div></div><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="forest" size="lg"><a href={directionsUrl} target="_blank" rel="noreferrer">Get directions <ArrowUpRight /></a></Button><Button asChild variant="outline" size="lg"><a href={phoneHref}><Phone /> Call hospital</a></Button></div></div><div className="relative min-h-[380px] overflow-hidden bg-sage lg:min-h-[610px]"><img src={exterior.url} alt="Entebbe Regional Referral Hospital building entrance" className="absolute inset-0 size-full object-cover object-center" /><div className="image-shade absolute inset-0" /><div className="absolute bottom-7 left-7 right-7 text-forest-foreground"><p className="eyebrow text-sun">Look for us here</p><p className="mt-2 text-2xl font-semibold">Entebbe Regional Referral Hospital</p><p className="mt-1 text-sm">Nsamizi Road, Entebbe</p></div></div></section>
  <section className="bg-sage py-12"><div className="site-container flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow text-primary">Before you come</p><h2 className="mt-3 text-2xl font-semibold">Looking for a particular service?</h2><p className="mt-2 text-sm text-ink-soft">Browse our care options and call to confirm clinic availability.</p></div><Button asChild variant="forest" size="lg"><Link to="/services">Explore services <ArrowUpRight /></Link></Button></div></section>
  <section className="site-container py-10"><p className="text-xs leading-6 text-muted-foreground">Contact number and street address listed by <a href="https://www.medpages.info/sf/index.php?orgcode=307187&page=organisation" target="_blank" rel="noreferrer" className="underline">Medpages</a>. Please verify details directly with the hospital.</p></section>
  </>; }